name: khmer_cultur_app
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  smooth_page_indicator: ^2.0.1
  device_preview: ^1.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  sqflite: ^2.4.2
  google_maps_flutter: ^2.12.2
  flutter_secure_storage: ^9.0.0
  geolocator: ^9.0.2
  dio: ^5.9.0
  lucide_icons: 0.257.0
  url_launcher: ^6.3.1
  intl: ^0.20.2
  http: ^1.6.0
  shared_preferences: ^2.5.4
  fl_chart: ^1.0.0
  shimmer: ^3.0.0
  path: ^1.8.3
  jwt_decoder: ^2.0.1
  provider: ^6.1.2
  retry: ^3.1.2
  http_io: ^1.0.0
  connectivity_plus: ^6.0.5
  flutter_slidable: ^3.1.0
  google_fonts: ^6.1.0
  sizer: ^2.0.15
  location: ^6.0.0
  geocoding: ^3.0.0
  uuid: ^4.5.2
  mobile_scanner: ^5.0.0
  cupertino_icons: ^1.0.8
  dynamic_tabbar: ^1.0.9
  permission_handler: ^11.3.1
  photo_view: ^0.15.0
  image_picker: ^1.2.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: KhmerOSBattambang
      fonts:
        - asset: assets/fonts/KhmerOSbattambang.ttf
